### ISSUE TITLE
"add another work on this page" gives URL to reused work, not the URL to the original work

### ISSUE THREAD

**Issue by Taskamp** [project-octopus/octopodes#77]
If you click on "add another work on this page", you are directed to a new page. On that new page, the webpage URL that is already filled in refers to the URL of the reuse work of your former review, not to the URL of the original. I think it should be the URL of the original work instead.
![screen shot 2014-12-16 at 16 09 59](https://cloud.githubusercontent.com/assets/3542255/5455709/49a16b5a-853e-11e4-82fd-0cb6a135b026.png)

**Comment by christopheradams** [comment]
This exact interaction doesn't exist any more.
