### ISSUE TITLE
make work first class in data model

### ISSUE THREAD

**Issue by mlinksva** [project-octopus/octopodes#78]
Right now "original URL" identifies a work. This is inadequate for a variety of reasons including:

* multiple works at same page
* ambiguous, unknown, or changing location of "original" publication
* wrong basis for denoting relationships between works, eg a "web page url" is not the thing that is a remix of an "original url"
* inflexible basis for curating dataset, eg splitting and merging records about works as it is determined records are the same or not
* pre-(re)use entry into system, ie #58 

How to transition:

* Each work has a p-o URL like /work/$id
* For existing reviews (1) a new work record created for each "original URL" (populated with that field) and that field replaced with a "work" field pointing to new work record (2) a new review record created with "original URL" as the "web page URL" and the new work record as the "work"
* review form should also take "original URL" and either create and associate new work record, or just associate if there exists a work record with same "original URL"

work record should minimally have fields:

* original (publication) URL
* title
* creator
* license

The work record should be editable, meaning the default view version can be updated, but all revisions are kept.

**Comment by christopheradams** [comment]
Thanks Mike this is great feedback. This is the main issue I'll be tackling this week.

**Comment by christopheradams** [comment]
Closing. :) https://github.com/project-octopus/octopodes/blob/master/db/migrations/003_create_creative_works.rb
