### ISSUE TITLE
Main Add a Review Form Busted

### ISSUE THREAD

**Issue by rejon** [project-octopus/octopodes#82]
I tried to submit a review, and received a strange error about work not present, then the form erased, lost all my data... sad jon, discouraged me from taking the time intensive painful task of adding a review and work, and sent me off to the bar to drown my sorrow.

**Comment by rejon** [comment]
http://project-octopus.org/reviews;template

**Comment by christopheradams** [comment]
Should be fixed in 62a11b69d4fc3f05041b126899ba56328331e7b7. Some model validation code changed and I didn't have a test that would catch this.
